# Generated by Django 2.2.5 on 2020-03-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20200209_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.IntegerField(default=0),
        ),
    ]
