# Generated by Django 2.2.5 on 2020-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200303_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hours_activity',
            field=models.IntegerField(default=0),
        ),
    ]
