# Generated by Django 2.2.5 on 2020-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('protein', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
            ],
        ),
    ]
