# Generated by Django 2.2.5 on 2020-02-05 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0002_fooditem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('protein', models.IntegerField(default=0)),
                ('carb', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('fooditems', models.ManyToManyField(related_name='meals', to='nutrition.FoodItem')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealentries', to='nutrition.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealentries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
